
#ifndef SRCCPP_JLPPC_REGIMYS_PLAYERCORE_PLAYERCOREINCLUDE_HXX_
#define SRCCPP_JLPPC_REGIMYS_PLAYERCORE_PLAYERCOREINCLUDE_HXX_

#include "Equipe.hpp"
#include "Player.hpp"

#endif /* SRCCPP_JLPPC_REGIMYS_PLAYERCORE_PLAYERCOREINCLUDE_HXX_ */
